//===----------------------------------------------------------------------===//
//
// This source file is part of the SwiftNIO open source project
//
// Copyright (c) 2017-2018 Apple Inc. and the SwiftNIO project authors
// Licensed under Apache License v2.0
//
// See LICENSE.txt for license information
// See CONTRIBUTORS.txt for the list of SwiftNIO project authors
//
// SPDX-License-Identifier: Apache-2.0
//
//===----------------------------------------------------------------------===//
//
// ByteBufferBIOTest+XCTest.swift
//
import XCTest

///
/// NOTE: This file was generated by generate_linux_tests.rb
///
/// Do NOT edit this file directly as it will be regenerated automatically when needed.
///

extension ByteBufferBIOTest {

   static var allTests : [(String, (ByteBufferBIOTest) -> () throws -> Void)] {
      return [
                ("testExtractingBIOWrite", testExtractingBIOWrite),
                ("testManyBIOWritesAreCoalesced", testManyBIOWritesAreCoalesced),
                ("testReadWithNoDataInBIO", testReadWithNoDataInBIO),
                ("testReadWithDataInBIO", testReadWithDataInBIO),
                ("testShortReads", testShortReads),
                ("testDropRefToBaseObjectOnRead", testDropRefToBaseObjectOnRead),
                ("testDropRefToBaseObjectOnWrite", testDropRefToBaseObjectOnWrite),
                ("testZeroLengthReadsAlwaysSucceed", testZeroLengthReadsAlwaysSucceed),
                ("testWriteWhenHoldingBufferTriggersCoW", testWriteWhenHoldingBufferTriggersCoW),
                ("testWriteWhenDroppedBufferDoesNotTriggerCoW", testWriteWhenDroppedBufferDoesNotTriggerCoW),
                ("testZeroLengthWriteIsNoOp", testZeroLengthWriteIsNoOp),
                ("testSimplePuts", testSimplePuts),
                ("testGetsNotSupported", testGetsNotSupported),
                ("testBasicCtrlDance", testBasicCtrlDance),
           ]
   }
}

