//===----------------------------------------------------------------------===//
//
// This source file is part of the SwiftNIO open source project
//
// Copyright (c) 2017-2018 Apple Inc. and the SwiftNIO project authors
// Licensed under Apache License v2.0
//
// See LICENSE.txt for license information
// See CONTRIBUTORS.txt for the list of SwiftNIO project authors
//
// SPDX-License-Identifier: Apache-2.0
//
//===----------------------------------------------------------------------===//
//
// SSLPKCS12BundleTest+XCTest.swift
//
import XCTest

///
/// NOTE: This file was generated by generate_linux_tests.rb
///
/// Do NOT edit this file directly as it will be regenerated automatically when needed.
///

extension SSLPKCS12BundleTest {

   static var allTests : [(String, (SSLPKCS12BundleTest) -> () throws -> Void)] {
      return [
                ("testDecodingSimpleP12FromMemory", testDecodingSimpleP12FromMemory),
                ("testDecodingComplexP12FromMemory", testDecodingComplexP12FromMemory),
                ("testDecodingSimpleP12FromMemoryWithoutPassphrase", testDecodingSimpleP12FromMemoryWithoutPassphrase),
                ("testDecodingSimpleP12FromFile", testDecodingSimpleP12FromFile),
                ("testDecodingComplexP12FromFile", testDecodingComplexP12FromFile),
                ("testDecodingSimpleP12FromFileWithoutPassphrase", testDecodingSimpleP12FromFileWithoutPassphrase),
                ("testDecodingNonExistentPKCS12File", testDecodingNonExistentPKCS12File),
           ]
   }
}

